In [5]:
# enumerate
l1 = ['a', 'b', 'c']

print("Print the tupe object directly:")
for l in enumerate(l1, 100):
    print(l)
print("Print index and value separately:")
for count, l in enumerate(l1, 50):
    print(count, l)

Print the tupe object directly:
(100, 'a')
(101, 'b')
(102, 'c')
Print index and value separately:
50 a
51 b
52 c


In [2]:
# Test unique in numpy
import numpy as np

arr = np.array([[1, 2, 3, 1, 2]])
print(np.unique(arr))

[1 2 3]


In [7]:
# Test where function in numpy
np.where([[True, False], [False, True]], [[1, 2], [3, 4]], [[5, 6], [7, 8]])[0][:2]

array([1, 6])

In [18]:
# Test np.bincount

arr = np.array([1, 1, 2, 1, 3])
print(np.bincount(arr + 1))
print(arr==1)
arr2 = arr == 1
print(np.sum(arr2))
arr3 = np.array([1, 2, 3, 4, 5])
print(arr3[arr2])

[0 0 3 1 1]
[ True  True False  True False]
3
[1 2 4]


In [29]:
# Test iter
strTest = [1, 2, 1, 5 ,6 , 5]
tmp = zip(*[iter(strTest)]*2)
print(list(tmp))

[(1, 2), (1, 5), (6, 5)]
